### ISSUE TITLE
FYI: This is my Trivial brainfuck extension interpreter.

### ISSUE THREAD

**Issue by rdebath** [taco-c/Trainfuck#1]
``` ruby
#!/usr/bin/ruby
h = Hash.new{|_, k|
    if k[0] == "+" then "m[p]+="+k[1..-1]+';'
    elsif k[0] == "-" then "m[p]-="+k[1..-1]+';'
    elsif k[0] == ">" then "p+="+k[1..-1]+';'
    elsif k[0] == "<" then "p-="+k[1..-1]+';'
    end };

h.merge!({
        '>' => 'p+=1;',
        '<' => 'p-=1;',
        '+' => 'm[p]+=1;',
        '-' => 'm[p]-=1;',
        '[' => '(',
        ']' => ')while((m[p]&=255)!=0);',
        '.' => 'putc m[p];',
        ',' => 'm[p]=STDIN.getbyte if !STDIN.eof;',
        ':' => 'print (m[p]&255).to_s;',
        });

eval 'm=Hash.new(p=0);'+ARGF.read.gsub(/[-+><][0-9]+|./, h);
```

**Comment by taco-c** [comment]
That's nice, but, why did you write this here?

**Comment by rdebath** [comment]
It would probably have helped if I'd remembered to paste the link: https://esolangs.org/wiki/Brainfuck_extensions and the plea that you try to do something a little more original than adding a couple of "wimp mode" instructions.

**Comment by taco-c** [comment]
Well, this project is mostly for my own amusement, and testing my own abilities. I started this project only yesterday so it's in no way "finished" anyway.

But I appreciate the link, haven't seen that page before.
